# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.0'

# Web framework
gem 'sinatra', '~> 4.0'
gem 'sinatra-contrib', '~> 4.0'
gem 'puma', '~> 6.4'
gem 'rack-cors', '~> 2.0'

# Database
gem 'sequel', '~> 5.80'
gem 'pg', '~> 1.5'

# Auth
gem 'jwt', '~> 2.9'
gem 'bcrypt', '~> 3.1'

# HTTP Client
gem 'faraday', '~> 2.9'
gem 'faraday-retry', '~> 2.2'

# Validation
gem 'dry-validation', '~> 1.10'
gem 'dry-monads', '~> 1.6'

# Utilities
gem 'dotenv', '~> 3.1'
gem 'oj', '~> 3.16'

group :development, :test do
  gem 'rspec', '~> 3.13'
  gem 'rack-test', '~> 2.1'
  gem 'factory_bot', '~> 6.4'
  gem 'faker', '~> 3.3'
  gem 'database_cleaner-sequel', '~> 2.0'
  gem 'simplecov', '~> 0.22', require: false
  gem 'webmock', '~> 3.23'
  gem 'rubocop', '~> 1.65', require: false
  gem 'rubocop-rspec', '~> 3.0', require: false
end
